# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"
loaderVersion="[36,)"
license="GPL-3.0 License"
issueTrackerURL="https://github.com/grim3212/AssortedStorage"

[[mods]]
modId="assortedstorage"
version="${file.jarVersion}"
displayName="Assorted Storage"
#updateJSONURL=""
displayURL="https://assortedmods.com/storage"
logoFile="logo.png"
authors="Grim3212"
description='''
Assorted blocks and items useful for storage
'''

[[dependencies.assortedstorage]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assortedstorage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
